# Generated by Django 6.0.6 on 2026-07-30 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_paymentcheckoutsession_paymentsettlementbatch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentcheckoutsession',
            name='source_type',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('SALES_ORDER', 'Sales Order'), ('SALES_INVOICE', 'Sales Invoice'), ('SUBSCRIPTION', 'Subscription'), ('OTHER', 'Other')], default='MANUAL', max_length=40),
        ),
    ]
