# Generated by Django 6.0.6 on 2026-07-25 18:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0004_taxrate_calculation_base_taxrate_is_system_and_more'),
        ('accounts', '0001_initial'),
        ('companies', '0005_seed_activity_profiles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, default='')),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, max_length=50)),
                ('name_ar', models.CharField(db_index=True, max_length=180)),
                ('name_en', models.CharField(blank=True, db_index=True, default='', max_length=180)),
                ('description', models.TextField(blank=True, default='')),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_departments', to='companies.company')),
                ('cost_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_departments', to='accounting.costcenter')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(app_label)s_%(class)s_records', to=settings.AUTH_USER_MODEL)),
                ('manager_membership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_medical_departments', to='accounts.companymembership')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='medical.medicaldepartment')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(app_label)s_%(class)s_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['company_id', 'sort_order', 'name_ar', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MedicalClinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, default='')),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, max_length=60)),
                ('name_ar', models.CharField(db_index=True, max_length=180)),
                ('name_en', models.CharField(blank=True, db_index=True, default='', max_length=180)),
                ('room_number', models.CharField(blank=True, db_index=True, default='', max_length=60)),
                ('floor', models.CharField(blank=True, db_index=True, default='', max_length=60)),
                ('capacity', models.PositiveIntegerField(default=1)),
                ('opening_time', models.TimeField(blank=True, null=True)),
                ('closing_time', models.TimeField(blank=True, null=True)),
                ('is_default', models.BooleanField(db_index=True, default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('description', models.TextField(blank=True, default='')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medical_clinics', to='companies.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_clinics', to='companies.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(app_label)s_%(class)s_records', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(app_label)s_%(class)s_records', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clinics', to='medical.medicaldepartment')),
            ],
            options={
                'ordering': ['company_id', 'branch_id', 'department_id', 'code'],
            },
        ),
        migrations.CreateModel(
            name='MedicalDepartmentBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, default='')),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_primary', models.BooleanField(db_index=True, default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('opening_time', models.TimeField(blank=True, null=True)),
                ('closing_time', models.TimeField(blank=True, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medical_department_assignments', to='companies.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_department_branches', to='companies.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(app_label)s_%(class)s_records', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_assignments', to='medical.medicaldepartment')),
                ('manager_membership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_medical_department_branches', to='accounts.companymembership')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(app_label)s_%(class)s_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['company_id', 'department_id', '-is_primary', 'branch_id'],
            },
        ),
        migrations.CreateModel(
            name='MedicalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, default='')),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient_number_prefix', models.CharField(default='PAT', max_length=20)),
                ('practitioner_number_prefix', models.CharField(default='PRC', max_length=20)),
                ('default_appointment_duration', models.PositiveIntegerField(default=30)),
                ('require_patient_identifier', models.BooleanField(default=False)),
                ('allow_duplicate_patient_override', models.BooleanField(default=False)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical_settings', to='companies.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(app_label)s_%(class)s_records', to=settings.AUTH_USER_MODEL)),
                ('default_registration_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_medical_registration_settings', to='companies.branch')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(app_label)s_%(class)s_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Medical settings',
                'verbose_name_plural': 'Medical settings',
            },
        ),
        migrations.CreateModel(
            name='MedicalSpecialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, default='')),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, max_length=80)),
                ('name_ar', models.CharField(db_index=True, max_length=180)),
                ('name_en', models.CharField(blank=True, db_index=True, default='', max_length=180)),
                ('description', models.TextField(blank=True, default='')),
                ('is_system', models.BooleanField(db_index=True, default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medical_specialties', to='companies.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(app_label)s_%(class)s_records', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(app_label)s_%(class)s_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_system', 'sort_order', 'name_ar', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MedicalDepartmentSpecialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, default='')),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_primary', models.BooleanField(db_index=True, default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_department_specialties', to='companies.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(app_label)s_%(class)s_records', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialty_assignments', to='medical.medicaldepartment')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(app_label)s_%(class)s_records', to=settings.AUTH_USER_MODEL)),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='department_assignments', to='medical.medicalspecialty')),
            ],
            options={
                'ordering': ['company_id', 'department_id', '-is_primary', 'specialty_id'],
            },
        ),
        migrations.CreateModel(
            name='MedicalClinicSpecialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, default='')),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_primary', models.BooleanField(db_index=True, default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialty_assignments', to='medical.medicalclinic')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_clinic_specialties', to='companies.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(app_label)s_%(class)s_records', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(app_label)s_%(class)s_records', to=settings.AUTH_USER_MODEL)),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clinic_assignments', to='medical.medicalspecialty')),
            ],
            options={
                'ordering': ['company_id', 'clinic_id', '-is_primary', 'specialty_id'],
            },
        ),
        migrations.AddIndex(
            model_name='medicaldepartment',
            index=models.Index(fields=['company', 'is_active'], name='medical_med_company_175f2c_idx'),
        ),
        migrations.AddIndex(
            model_name='medicaldepartment',
            index=models.Index(fields=['company', 'parent'], name='medical_med_company_0d9cfa_idx'),
        ),
        migrations.AddIndex(
            model_name='medicaldepartment',
            index=models.Index(fields=['company', 'sort_order'], name='medical_med_company_989cfd_idx'),
        ),
        migrations.AddIndex(
            model_name='medicaldepartment',
            index=models.Index(fields=['company', 'cost_center'], name='medical_med_company_8d6ddf_idx'),
        ),
        migrations.AddConstraint(
            model_name='medicaldepartment',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='medical_dept_code_company_uniq'),
        ),
        migrations.AddIndex(
            model_name='medicalclinic',
            index=models.Index(fields=['company', 'branch', 'is_active'], name='medical_med_company_b63aa9_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalclinic',
            index=models.Index(fields=['company', 'department', 'is_active'], name='medical_med_company_d37f3d_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalclinic',
            index=models.Index(fields=['company', 'is_default'], name='medical_med_company_3e26d0_idx'),
        ),
        migrations.AddConstraint(
            model_name='medicalclinic',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='medical_clinic_code_company_uniq'),
        ),
        migrations.AddConstraint(
            model_name='medicalclinic',
            constraint=models.UniqueConstraint(condition=models.Q(('room_number', ''), _negated=True), fields=('branch', 'room_number'), name='medical_clinic_room_branch_uniq'),
        ),
        migrations.AddConstraint(
            model_name='medicalclinic',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('company', 'branch', 'department'), name='medical_clinic_default_uniq'),
        ),
        migrations.AddIndex(
            model_name='medicaldepartmentbranch',
            index=models.Index(fields=['company', 'branch', 'is_active'], name='medical_med_company_411e04_idx'),
        ),
        migrations.AddIndex(
            model_name='medicaldepartmentbranch',
            index=models.Index(fields=['company', 'department', 'is_active'], name='medical_med_company_59d3c1_idx'),
        ),
        migrations.AddConstraint(
            model_name='medicaldepartmentbranch',
            constraint=models.UniqueConstraint(fields=('department', 'branch'), name='medical_dept_branch_uniq'),
        ),
        migrations.AddIndex(
            model_name='medicalspecialty',
            index=models.Index(fields=['company', 'is_system', 'is_active'], name='medical_med_company_07a3ac_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalspecialty',
            index=models.Index(fields=['code', 'is_active'], name='medical_med_code_609387_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalspecialty',
            index=models.Index(fields=['sort_order', 'is_active'], name='medical_med_sort_or_609a65_idx'),
        ),
        migrations.AddConstraint(
            model_name='medicalspecialty',
            constraint=models.UniqueConstraint(condition=models.Q(('company__isnull', True)), fields=('code',), name='medical_specialty_system_code_uniq'),
        ),
        migrations.AddConstraint(
            model_name='medicalspecialty',
            constraint=models.UniqueConstraint(condition=models.Q(('company__isnull', False)), fields=('company', 'code'), name='medical_specialty_company_code_uniq'),
        ),
        migrations.AddConstraint(
            model_name='medicalspecialty',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('company__isnull', True), ('is_system', True)), models.Q(('company__isnull', False), ('is_system', False)), _connector='OR'), name='medical_specialty_scope_check'),
        ),
        migrations.AddIndex(
            model_name='medicaldepartmentspecialty',
            index=models.Index(fields=['company', 'department', 'is_active'], name='medical_med_company_98f6bc_idx'),
        ),
        migrations.AddIndex(
            model_name='medicaldepartmentspecialty',
            index=models.Index(fields=['company', 'specialty', 'is_active'], name='medical_med_company_c008de_idx'),
        ),
        migrations.AddConstraint(
            model_name='medicaldepartmentspecialty',
            constraint=models.UniqueConstraint(fields=('department', 'specialty'), name='medical_dept_specialty_uniq'),
        ),
        migrations.AddIndex(
            model_name='medicalclinicspecialty',
            index=models.Index(fields=['company', 'clinic', 'is_active'], name='medical_med_company_67075c_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalclinicspecialty',
            index=models.Index(fields=['company', 'specialty', 'is_active'], name='medical_med_company_33c0ef_idx'),
        ),
        migrations.AddConstraint(
            model_name='medicalclinicspecialty',
            constraint=models.UniqueConstraint(fields=('clinic', 'specialty'), name='medical_clinic_specialty_uniq'),
        ),
    ]
