# Generated by Django 6.0.6 on 2026-07-25 19:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('companies', '0005_seed_activity_profiles'),
        ('hr', '0005_performancecriterion_performancecycle_and_more'),
        ('medical', '0002_seed_system_specialties'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalPractitioner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('practitioner_number', models.CharField(max_length=50)),
                ('full_name_ar', models.CharField(blank=True, default='', max_length=220)),
                ('full_name_en', models.CharField(blank=True, default='', max_length=220)),
                ('professional_title', models.CharField(blank=True, default='', max_length=160)),
                ('practitioner_type', models.CharField(choices=[('PHYSICIAN', 'Physician'), ('DENTIST', 'Dentist'), ('NURSE', 'Nurse'), ('PHARMACIST', 'Pharmacist'), ('TECHNICIAN', 'Technician'), ('THERAPIST', 'Therapist'), ('OTHER', 'Other')], default='PHYSICIAN', max_length=30)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('UNSPECIFIED', 'Unspecified')], default='UNSPECIFIED', max_length=20)),
                ('nationality', models.CharField(blank=True, default='', max_length=120)),
                ('mobile', models.CharField(blank=True, default='', max_length=30)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('hire_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('SUSPENDED', 'Suspended'), ('ON_LEAVE', 'On leave')], default='ACTIVE', max_length=20)),
                ('is_accepting_appointments', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_practitioners', to='companies.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(app_label)s_%(class)s_records', to=settings.AUTH_USER_MODEL)),
                ('default_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='default_medical_practitioners', to='companies.branch')),
                ('default_clinic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='default_practitioners', to='medical.medicalclinic')),
                ('default_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='default_practitioners', to='medical.medicaldepartment')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='medical_practitioner_profiles', to='hr.employee')),
                ('membership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='medical_practitioner_profiles', to='accounts.companymembership')),
                ('primary_specialty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='primary_practitioners', to='medical.medicalspecialty')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(app_label)s_%(class)s_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['company_id', 'practitioner_number', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MedicalPractitionerAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('working_hours', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True, default='')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medical_practitioner_assignments', to='companies.branch')),
                ('clinic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='practitioner_assignments', to='medical.medicalclinic')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_practitioner_assignments', to='companies.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(app_label)s_%(class)s_records', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='practitioner_assignments', to='medical.medicaldepartment')),
                ('practitioner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_assignments', to='medical.medicalpractitioner')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(app_label)s_%(class)s_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['company_id', 'practitioner_id', '-is_primary', 'branch_id', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MedicalPractitionerLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('license_number', models.CharField(max_length=100)),
                ('license_type', models.CharField(blank=True, default='', max_length=120)),
                ('issuing_authority', models.CharField(max_length=180)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('SUSPENDED', 'Suspended'), ('REVOKED', 'Revoked')], default='PENDING', max_length=20)),
                ('issued_at', models.DateField(blank=True, null=True)),
                ('expires_at', models.DateField(blank=True, null=True)),
                ('verified_at', models.DateField(blank=True, null=True)),
                ('document_reference', models.CharField(blank=True, default='', max_length=255)),
                ('notes', models.TextField(blank=True, default='')),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_practitioner_licenses', to='companies.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(app_label)s_%(class)s_records', to=settings.AUTH_USER_MODEL)),
                ('practitioner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to='medical.medicalpractitioner')),
                ('specialty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='practitioner_licenses', to='medical.medicalspecialty')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(app_label)s_%(class)s_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['company_id', 'practitioner_id', 'license_number', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MedicalPractitionerSpecialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('years_experience', models.PositiveIntegerField(default=0)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_practitioner_specialties', to='companies.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(app_label)s_%(class)s_records', to=settings.AUTH_USER_MODEL)),
                ('practitioner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialty_assignments', to='medical.medicalpractitioner')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='practitioner_assignments', to='medical.medicalspecialty')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(app_label)s_%(class)s_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['company_id', 'practitioner_id', '-is_primary', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='medicalpractitioner',
            index=models.Index(fields=['company', 'status'], name='medical_med_company_586729_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalpractitioner',
            index=models.Index(fields=['company', 'practitioner_type'], name='medical_med_company_4f771b_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalpractitioner',
            index=models.Index(fields=['company', 'primary_specialty'], name='medical_med_company_96f48a_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalpractitioner',
            index=models.Index(fields=['company', 'default_branch'], name='medical_med_company_1d69fc_idx'),
        ),
        migrations.AddConstraint(
            model_name='medicalpractitioner',
            constraint=models.UniqueConstraint(fields=('company', 'practitioner_number'), name='medical_practitioner_number_company_uniq'),
        ),
        migrations.AddConstraint(
            model_name='medicalpractitioner',
            constraint=models.UniqueConstraint(condition=models.Q(('membership__isnull', False)), fields=('company', 'membership'), name='medical_practitioner_membership_uniq'),
        ),
        migrations.AddConstraint(
            model_name='medicalpractitioner',
            constraint=models.UniqueConstraint(condition=models.Q(('employee__isnull', False)), fields=('company', 'employee'), name='medical_practitioner_employee_uniq'),
        ),
        migrations.AddIndex(
            model_name='medicalpractitionerassignment',
            index=models.Index(fields=['company', 'branch', 'is_active'], name='medical_med_company_af5e18_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalpractitionerassignment',
            index=models.Index(fields=['company', 'department', 'is_active'], name='medical_med_company_c2dc46_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalpractitionerassignment',
            index=models.Index(fields=['company', 'clinic', 'is_active'], name='medical_med_company_7182af_idx'),
        ),
        migrations.AddConstraint(
            model_name='medicalpractitionerassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('is_primary', True)), fields=('practitioner',), name='medical_practitioner_primary_assignment_uniq'),
        ),
        migrations.AddIndex(
            model_name='medicalpractitionerlicense',
            index=models.Index(fields=['company', 'status'], name='medical_med_company_56037f_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalpractitionerlicense',
            index=models.Index(fields=['company', 'expires_at'], name='medical_med_company_f91a1b_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalpractitionerlicense',
            index=models.Index(fields=['company', 'practitioner'], name='medical_med_company_d15d92_idx'),
        ),
        migrations.AddConstraint(
            model_name='medicalpractitionerlicense',
            constraint=models.UniqueConstraint(fields=('company', 'license_number'), name='medical_license_number_company_uniq'),
        ),
        migrations.AddIndex(
            model_name='medicalpractitionerspecialty',
            index=models.Index(fields=['company', 'specialty', 'is_active'], name='medical_med_company_973df1_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalpractitionerspecialty',
            index=models.Index(fields=['company', 'practitioner', 'is_active'], name='medical_med_company_ae808a_idx'),
        ),
        migrations.AddConstraint(
            model_name='medicalpractitionerspecialty',
            constraint=models.UniqueConstraint(fields=('practitioner', 'specialty'), name='medical_practitioner_specialty_uniq'),
        ),
        migrations.AddConstraint(
            model_name='medicalpractitionerspecialty',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('is_primary', True)), fields=('practitioner',), name='medical_practitioner_primary_specialty_uniq'),
        ),
    ]
