# Generated by Django 6.0.6 on 2026-07-26 10:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_backends', '0001_initial'),
        ('companies', '0005_seed_activity_profiles'),
        ('medical', '0003_medicalpractitioner_medicalpractitionerassignment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalPatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_number', models.CharField(db_index=True, max_length=80)),
                ('identifier_type', models.CharField(choices=[('NATIONAL_ID', 'National ID'), ('IQAMA', 'Iqama'), ('PASSPORT', 'Passport'), ('OTHER', 'Other'), ('UNSPECIFIED', 'Unspecified')], db_index=True, default='UNSPECIFIED', max_length=20)),
                ('identifier_number', models.CharField(blank=True, db_index=True, default='', max_length=80)),
                ('full_name', models.CharField(db_index=True, max_length=220)),
                ('full_name_ar', models.CharField(blank=True, default='', max_length=220)),
                ('full_name_en', models.CharField(blank=True, default='', max_length=220)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other'), ('UNSPECIFIED', 'Unspecified')], db_index=True, default='UNSPECIFIED', max_length=20)),
                ('nationality', models.CharField(blank=True, default='', max_length=100)),
                ('mobile', models.CharField(blank=True, db_index=True, default='', max_length=50)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('DECEASED', 'Deceased'), ('BLOCKED', 'Blocked')], db_index=True, default='ACTIVE', max_length=20)),
                ('registered_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True, default='')),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_patients', to='companies.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_medical_patient_records', to=settings.AUTH_USER_MODEL)),
                ('legacy_patient', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_patient', to='activity_backends.clinicpatient')),
                ('registration_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registered_medical_patients', to='companies.branch')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_medical_patient_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['company_id', 'full_name', 'id'],
                'indexes': [models.Index(fields=['company', 'status'], name='medical_med_company_c191b6_idx'), models.Index(fields=['company', 'mobile'], name='medical_med_company_0a56e2_idx'), models.Index(fields=['company', 'full_name'], name='medical_med_company_9ff296_idx'), models.Index(fields=['company', 'registration_branch'], name='medical_med_company_503e2d_idx'), models.Index(fields=['company', 'registered_at'], name='medical_med_company_3084e6_idx')],
                'constraints': [models.UniqueConstraint(fields=('company', 'patient_number'), name='medical_patient_number_company_uniq'), models.UniqueConstraint(condition=models.Q(('identifier_number', ''), _negated=True), fields=('company', 'identifier_number'), name='medical_patient_identifier_company_uniq')],
            },
        ),
    ]
