# Generated by Django 6.0.6 on 2026-07-27 05:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_backends', '0003_link_appointments_to_medical_patients'),
        ('companies', '0005_seed_activity_profiles'),
        ('medical', '0005_migrate_legacy_patients'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_number', models.CharField(db_index=True, max_length=80)),
                ('scheduled_start', models.DateTimeField(db_index=True)),
                ('scheduled_end', models.DateTimeField(db_index=True)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('CONFIRMED', 'Confirmed'), ('CHECKED_IN', 'Checked in'), ('IN_PROGRESS', 'In progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('NO_SHOW', 'No show')], db_index=True, default='SCHEDULED', max_length=20)),
                ('source', models.CharField(choices=[('MANUAL', 'Manual'), ('PHONE', 'Phone'), ('ONLINE', 'Online'), ('WHATSAPP', 'WhatsApp'), ('WALK_IN', 'Walk in'), ('LEGACY', 'Legacy')], db_index=True, default='MANUAL', max_length=20)),
                ('reason', models.CharField(blank=True, default='', max_length=300)),
                ('practitioner_name_snapshot', models.CharField(blank=True, default='', max_length=220)),
                ('service_name_snapshot', models.CharField(blank=True, default='', max_length=220)),
                ('price_snapshot', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True, default='')),
                ('cancellation_reason', models.TextField(blank=True, default='')),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('no_show_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='medical_appointments', to='companies.branch')),
                ('clinic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='medical.medicalclinic')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_appointments', to='companies.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_medical_appointments', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='medical.medicaldepartment')),
                ('legacy_appointment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_appointment', to='activity_backends.clinicappointment')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='medical.medicalpatient')),
                ('practitioner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='medical.medicalpractitioner')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_medical_appointments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['company_id', '-scheduled_start', 'id'],
                'indexes': [models.Index(fields=['company', 'status', 'scheduled_start'], name='medical_med_company_28c841_idx'), models.Index(fields=['company', 'branch', 'scheduled_start'], name='medical_med_company_5a7764_idx'), models.Index(fields=['company', 'practitioner', 'scheduled_start'], name='medical_med_company_4ac0b8_idx'), models.Index(fields=['patient', 'scheduled_start'], name='medical_med_patient_4b46dd_idx')],
                'constraints': [models.UniqueConstraint(fields=('company', 'appointment_number'), name='medical_appointment_number_company_uniq'), models.CheckConstraint(condition=models.Q(('scheduled_end__gt', models.F('scheduled_start'))), name='medical_appointment_end_after_start')],
            },
        ),
    ]
