# Generated by Django 6.0.6 on 2026-07-27 07:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_seed_activity_profiles'),
        ('medical', '0006_add_medical_appointment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalEncounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encounter_number', models.CharField(db_index=True, max_length=80)),
                ('encounter_type', models.CharField(choices=[('CONSULTATION', 'Consultation'), ('FOLLOW_UP', 'Follow up'), ('PROCEDURE', 'Procedure'), ('EMERGENCY', 'Emergency'), ('OTHER', 'Other')], db_index=True, default='CONSULTATION', max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('OPEN', 'Open'), ('IN_PROGRESS', 'In progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=20)),
                ('chief_complaint', models.TextField(blank=True, default='')),
                ('history_of_present_illness', models.TextField(blank=True, default='')),
                ('clinical_notes', models.TextField(blank=True, default='')),
                ('treatment_plan', models.TextField(blank=True, default='')),
                ('follow_up_plan', models.TextField(blank=True, default='')),
                ('opened_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encounter', to='medical.medicalappointment')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='medical_encounters', to='companies.branch')),
                ('clinic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='encounters', to='medical.medicalclinic')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_medical_encounters', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_encounters', to='companies.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_medical_encounters', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='encounters', to='medical.medicaldepartment')),
                ('opened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opened_medical_encounters', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='encounters', to='medical.medicalpatient')),
                ('practitioner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='encounters', to='medical.medicalpractitioner')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_medical_encounters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['company_id', '-opened_at', 'id'],
                'indexes': [models.Index(fields=['company', 'status', 'opened_at'], name='medical_med_company_371eb3_idx'), models.Index(fields=['patient', 'opened_at'], name='medical_med_patient_8c9771_idx'), models.Index(fields=['company', 'practitioner', 'opened_at'], name='medical_med_company_7c2e75_idx')],
                'constraints': [models.UniqueConstraint(fields=('company', 'encounter_number'), name='medical_encounter_number_company_uniq'), models.CheckConstraint(condition=models.Q(('closed_at__isnull', True), ('closed_at__gte', models.F('opened_at')), _connector='OR'), name='medical_encounter_closed_after_opened')],
            },
        ),
    ]
