# Generated by Django 6.0.6 on 2026-07-27 08:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_catalogitem_inventory_tracking_method_and_more'),
        ('companies', '0005_seed_activity_profiles'),
        ('medical', '0007_add_medical_encounter'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalDiagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis_code', models.CharField(blank=True, db_index=True, default='', max_length=80)),
                ('diagnosis_name', models.CharField(db_index=True, max_length=255)),
                ('is_primary', models.BooleanField(db_index=True, default=False)),
                ('diagnosed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True, default='')),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_diagnoses', to='companies.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_medical_diagnoses', to=settings.AUTH_USER_MODEL)),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to='medical.medicalencounter')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diagnoses', to='medical.medicalpatient')),
                ('practitioner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='diagnoses', to='medical.medicalpractitioner')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_medical_diagnoses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['company_id', 'encounter_id', '-is_primary', 'diagnosed_at', 'id'],
                'indexes': [models.Index(fields=['company', 'diagnosed_at'], name='medical_med_company_3c8d70_idx'), models.Index(fields=['patient', 'diagnosed_at'], name='medical_med_patient_6df199_idx'), models.Index(fields=['encounter', 'is_primary'], name='medical_med_encount_a209de_idx'), models.Index(fields=['company', 'diagnosis_code'], name='medical_med_company_bcc91c_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('encounter',), name='medical_primary_diagnosis_encounter_uniq')],
            },
        ),
        migrations.CreateModel(
            name='MedicalProcedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedure_code_snapshot', models.CharField(blank=True, db_index=True, default='', max_length=80)),
                ('procedure_name_snapshot', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('IN_PROGRESS', 'In progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='PLANNED', max_length=20)),
                ('quantity', models.DecimalField(decimal_places=3, default=1, max_digits=12)),
                ('unit_price_snapshot', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('performed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('catalog_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_procedures', to='catalog.catalogitem')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_procedures', to='companies.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_medical_procedures', to=settings.AUTH_USER_MODEL)),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedures', to='medical.medicalencounter')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='procedures', to='medical.medicalpatient')),
                ('practitioner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='performed_medical_procedures', to='medical.medicalpractitioner')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_medical_procedures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['company_id', 'encounter_id', 'created_at', 'id'],
                'indexes': [models.Index(fields=['company', 'status', 'created_at'], name='medical_med_company_da2e1c_idx'), models.Index(fields=['patient', 'performed_at'], name='medical_med_patient_1bf1d8_idx'), models.Index(fields=['encounter', 'status'], name='medical_med_encount_9d03e5_idx'), models.Index(fields=['company', 'procedure_code_snapshot'], name='medical_med_company_560c66_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='medical_procedure_quantity_positive'), models.CheckConstraint(condition=models.Q(('unit_price_snapshot__isnull', True), ('unit_price_snapshot__gte', 0), _connector='OR'), name='medical_procedure_price_nonnegative')],
            },
        ),
    ]
