# Generated by Django 6.0.6 on 2026-07-27 09:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_seed_activity_profiles'),
        ('medical', '0008_add_diagnoses_and_procedures'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalReferral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_number', models.CharField(db_index=True, max_length=80)),
                ('priority', models.CharField(choices=[('ROUTINE', 'Routine'), ('URGENT', 'Urgent'), ('EMERGENCY', 'Emergency')], db_index=True, default='ROUTINE', max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Sent'), ('ACCEPTED', 'Accepted'), ('IN_PROGRESS', 'In progress'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], db_index=True, default='DRAFT', max_length=20)),
                ('referral_reason', models.TextField()),
                ('clinical_summary', models.TextField(blank=True, default='')),
                ('requested_service', models.TextField(blank=True, default='')),
                ('referred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('cancellation_reason', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_medical_referrals', to=settings.AUTH_USER_MODEL)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_medical_referrals', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_referrals', to='companies.company')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_medical_referrals', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_medical_referrals', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medical_referrals', to='medical.medicalpatient')),
                ('receiving_practitioner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='medical_referrals_received', to='medical.medicalpractitioner')),
                ('referring_practitioner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medical_referrals_sent', to='medical.medicalpractitioner')),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_medical_referrals', to=settings.AUTH_USER_MODEL)),
                ('source_encounter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_referrals', to='medical.medicalencounter')),
                ('target_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='medical_referrals_received', to='companies.branch')),
                ('target_clinic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='medical_referrals_received', to='medical.medicalclinic')),
                ('target_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='medical_referrals_received', to='medical.medicaldepartment')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_medical_referrals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['company_id', '-referred_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MedicalReferralRecordAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('SUMMARY', 'Patient summary'), ('SOURCE_ENCOUNTER', 'Source encounter'), ('FULL_RECORD', 'Full medical record'), ('CUSTOM', 'Custom sections')], db_index=True, default='SUMMARY', max_length=30)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('REJECTED', 'Rejected'), ('REVOKED', 'Revoked'), ('EXPIRED', 'Expired')], db_index=True, default='PENDING', max_length=20)),
                ('shared_sections', models.JSONField(blank=True, default=list)),
                ('access_starts_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('access_ends_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('granted_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revocation_reason', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_medical_record_accesses', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_referral_record_accesses', to='companies.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_medical_record_accesses', to=settings.AUTH_USER_MODEL)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_medical_record_accesses', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medical_referral_record_accesses', to='medical.medicalpatient')),
                ('receiving_practitioner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='medical_record_accesses', to='medical.medicalpractitioner')),
                ('referral', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='record_access', to='medical.medicalreferral')),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_medical_record_accesses', to=settings.AUTH_USER_MODEL)),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_medical_record_accesses', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_medical_record_accesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['company_id', '-created_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='medicalreferral',
            index=models.Index(fields=['company', 'status', 'referred_at'], name='medical_med_company_0b50bc_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalreferral',
            index=models.Index(fields=['patient', 'referred_at'], name='medical_med_patient_d79627_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalreferral',
            index=models.Index(fields=['company', 'referring_practitioner', 'referred_at'], name='medical_med_company_99cbf7_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalreferral',
            index=models.Index(fields=['company', 'receiving_practitioner', 'status'], name='medical_med_company_1ffbf1_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalreferral',
            index=models.Index(fields=['company', 'target_branch', 'status'], name='medical_med_company_5e2fb2_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalreferral',
            index=models.Index(fields=['company', 'target_department', 'status'], name='medical_med_company_ccecfd_idx'),
        ),
        migrations.AddConstraint(
            model_name='medicalreferral',
            constraint=models.UniqueConstraint(fields=('company', 'referral_number'), name='medical_referral_number_company_uniq'),
        ),
        migrations.AddIndex(
            model_name='medicalreferralrecordaccess',
            index=models.Index(fields=['company', 'status', 'access_starts_at'], name='medical_med_company_8a8ba4_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalreferralrecordaccess',
            index=models.Index(fields=['patient', 'status'], name='medical_med_patient_c27db5_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalreferralrecordaccess',
            index=models.Index(fields=['company', 'receiving_practitioner', 'status'], name='medical_med_company_1936c2_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalreferralrecordaccess',
            index=models.Index(fields=['company', 'access_ends_at'], name='medical_med_company_3da7c4_idx'),
        ),
    ]
