# Generated by Django 6.0.6 on 2026-07-27 22:06

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_catalogitem_inventory_tracking_method_and_more'),
        ('companies', '0005_seed_activity_profiles'),
        ('medical', '0009_add_medical_referrals'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalServiceOffering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, default='')),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('ARCHIVED', 'Archived')], db_index=True, default='ACTIVE', max_length=20)),
                ('duration_minutes', models.PositiveSmallIntegerField(default=30, help_text='Clinical service duration in minutes.')),
                ('buffer_before_minutes', models.PositiveSmallIntegerField(default=0, help_text='Preparation time reserved before the appointment.')),
                ('buffer_after_minutes', models.PositiveSmallIntegerField(default=0, help_text='Cleanup or recovery time reserved after the appointment.')),
                ('sale_price_override', models.DecimalField(blank=True, decimal_places=2, help_text='Optional location-specific price. CatalogItem.sale_price is used when empty.', max_digits=14, null=True)),
                ('default_session_count', models.PositiveSmallIntegerField(default=1)),
                ('online_booking_enabled', models.BooleanField(db_index=True, default=False)),
                ('requires_approval', models.BooleanField(db_index=True, default=False)),
                ('requires_preparation', models.BooleanField(db_index=True, default=False)),
                ('preparation_instructions', models.TextField(blank=True, default='')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medical_service_offerings', to='companies.branch')),
                ('catalog_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medical_service_offerings', to='catalog.catalogitem')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_offerings', to='medical.medicalclinic')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_service_offerings', to='companies.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(app_label)s_%(class)s_records', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_offerings', to='medical.medicaldepartment')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_offerings', to='medical.medicalspecialty')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(app_label)s_%(class)s_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Medical Service Offering',
                'verbose_name_plural': 'Medical Service Offerings',
                'ordering': ['branch_id', 'department_id', 'clinic_id', 'catalog_item_id', 'id'],
                'indexes': [models.Index(fields=['company', 'status'], name='medical_off_company_status_idx'), models.Index(fields=['company', 'catalog_item'], name='medical_off_company_item_idx'), models.Index(fields=['company', 'branch', 'clinic', 'status'], name='medical_off_location_idx'), models.Index(fields=['company', 'specialty', 'status'], name='medical_off_specialty_idx'), models.Index(fields=['company', 'online_booking_enabled', 'status'], name='medical_off_online_idx')],
                'constraints': [models.UniqueConstraint(fields=('company', 'catalog_item', 'branch', 'department', 'specialty', 'clinic'), name='unique_medical_service_offering_scope'), models.CheckConstraint(condition=models.Q(('duration_minutes__gt', 0)), name='medical_service_offering_duration_positive'), models.CheckConstraint(condition=models.Q(('default_session_count__gt', 0)), name='medical_service_offering_sessions_positive'), models.CheckConstraint(condition=models.Q(('sale_price_override__isnull', True), ('sale_price_override__gte', Decimal('0.00')), _connector='OR'), name='medical_service_offering_price_nonnegative')],
            },
        ),
    ]
