# Generated by Django 6.0.6 on 2026-07-28 07:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_seed_activity_profiles'),
        ('medical', '0010_add_medical_service_offering'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalPractitionerServiceAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, default='')),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('ARCHIVED', 'Archived')], db_index=True, default='ACTIVE', max_length=20)),
                ('duration_override_minutes', models.PositiveSmallIntegerField(blank=True, help_text='Optional practitioner-specific clinical duration. Offering duration is inherited when empty.', null=True)),
                ('online_booking_enabled', models.BooleanField(blank=True, default=None, help_text='Optional practitioner-specific booking override. Offering setting is inherited when empty.', null=True)),
                ('effective_from', models.DateField(blank=True, db_index=True, null=True)),
                ('effective_until', models.DateField(blank=True, db_index=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_practitioner_service_assignments', to='companies.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(app_label)s_%(class)s_records', to=settings.AUTH_USER_MODEL)),
                ('practitioner_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_assignments', to='medical.medicalpractitionerassignment')),
                ('service_offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practitioner_assignments', to='medical.medicalserviceoffering')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(app_label)s_%(class)s_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Medical Practitioner Service Assignment',
                'verbose_name_plural': 'Medical Practitioner Service Assignments',
                'ordering': ['company_id', 'practitioner_assignment_id', 'service_offering_id', 'id'],
                'indexes': [models.Index(fields=['company', 'status'], name='med_psa_company_status'), models.Index(fields=['company', 'practitioner_assignment', 'status'], name='med_psa_practitioner'), models.Index(fields=['company', 'service_offering', 'status'], name='med_psa_offering_status'), models.Index(fields=['company', 'effective_from', 'effective_until'], name='med_psa_effective_dates')],
                'constraints': [models.UniqueConstraint(fields=('company', 'practitioner_assignment', 'service_offering'), name='med_psa_scope_uniq'), models.CheckConstraint(condition=models.Q(('duration_override_minutes__isnull', True), ('duration_override_minutes__gt', 0), _connector='OR'), name='med_psa_duration_pos')],
            },
        ),
    ]
