# Generated by Django 6.0.6 on 2026-07-28 09:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_seed_activity_profiles'),
        ('medical', '0011_add_practitioner_service_assignment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalPractitionerWeeklySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, default='')),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], db_index=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('slot_interval_minutes', models.PositiveSmallIntegerField(default=15, help_text='Minimum interval between generated appointment starting times.')),
                ('effective_from', models.DateField(blank=True, db_index=True, null=True)),
                ('effective_until', models.DateField(blank=True, db_index=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_practitioner_weekly_schedules', to='companies.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(app_label)s_%(class)s_records', to=settings.AUTH_USER_MODEL)),
                ('practitioner_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_schedules', to='medical.medicalpractitionerassignment')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(app_label)s_%(class)s_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Medical Practitioner Weekly Schedule',
                'verbose_name_plural': 'Medical Practitioner Weekly Schedules',
                'ordering': ['practitioner_assignment_id', 'weekday', 'start_time', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MedicalPractitionerScheduleBreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, default='')),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_practitioner_schedule_breaks', to='companies.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(app_label)s_%(class)s_records', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(app_label)s_%(class)s_records', to=settings.AUTH_USER_MODEL)),
                ('weekly_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_breaks', to='medical.medicalpractitionerweeklyschedule')),
            ],
            options={
                'verbose_name': 'Medical Practitioner Schedule Break',
                'verbose_name_plural': 'Medical Practitioner Schedule Breaks',
                'ordering': ['weekly_schedule_id', 'start_time', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MedicalPractitionerTimeOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, default='')),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('starts_at', models.DateTimeField(db_index=True)),
                ('ends_at', models.DateTimeField(db_index=True)),
                ('status', models.CharField(choices=[('APPROVED', 'Approved'), ('CANCELLED', 'Cancelled')], db_index=True, default='APPROVED', max_length=20)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_practitioner_time_offs', to='companies.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(app_label)s_%(class)s_records', to=settings.AUTH_USER_MODEL)),
                ('practitioner_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_off_periods', to='medical.medicalpractitionerassignment')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(app_label)s_%(class)s_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Medical Practitioner Time Off',
                'verbose_name_plural': 'Medical Practitioner Time Offs',
                'ordering': ['starts_at', 'practitioner_assignment_id', 'id'],
                'indexes': [models.Index(fields=['company', 'practitioner_assignment', 'starts_at', 'ends_at'], name='med_pto_assignment_dates'), models.Index(fields=['company', 'status', 'starts_at'], name='med_pto_status_start')],
            },
        ),
        migrations.AddIndex(
            model_name='medicalpractitionerweeklyschedule',
            index=models.Index(fields=['company', 'is_active'], name='med_pws_company_active'),
        ),
        migrations.AddIndex(
            model_name='medicalpractitionerweeklyschedule',
            index=models.Index(fields=['company', 'practitioner_assignment', 'weekday'], name='med_pws_assignment_day'),
        ),
        migrations.AddIndex(
            model_name='medicalpractitionerweeklyschedule',
            index=models.Index(fields=['company', 'effective_from', 'effective_until'], name='med_pws_effective_dates'),
        ),
        migrations.AddConstraint(
            model_name='medicalpractitionerweeklyschedule',
            constraint=models.UniqueConstraint(fields=('company', 'practitioner_assignment', 'weekday', 'start_time', 'end_time'), name='med_pws_unique_shift'),
        ),
        migrations.AddConstraint(
            model_name='medicalpractitionerweeklyschedule',
            constraint=models.CheckConstraint(condition=models.Q(('slot_interval_minutes__gt', 0)), name='med_pws_interval_positive'),
        ),
        migrations.AddIndex(
            model_name='medicalpractitionerschedulebreak',
            index=models.Index(fields=['company', 'weekly_schedule', 'is_active'], name='med_psb_schedule_active'),
        ),
        migrations.AddConstraint(
            model_name='medicalpractitionerschedulebreak',
            constraint=models.UniqueConstraint(fields=('company', 'weekly_schedule', 'start_time', 'end_time'), name='med_psb_unique_window'),
        ),
    ]
