# Generated by Django 6.0.6 on 2026-07-28 11:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_backends', '0003_link_appointments_to_medical_patients'),
        ('companies', '0005_seed_activity_profiles'),
        ('medical', '0012_add_practitioner_availability'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalappointment',
            name='practitioner_assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='medical_appointments', to='medical.medicalpractitionerassignment'),
        ),
        migrations.AddField(
            model_name='medicalappointment',
            name='practitioner_service_assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='medical_appointments', to='medical.medicalpractitionerserviceassignment'),
        ),
        migrations.AlterField(
            model_name='medicalappointment',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SCHEDULED', 'Scheduled'), ('CONFIRMED', 'Confirmed'), ('CHECKED_IN', 'Checked in'), ('IN_PROGRESS', 'In progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('NO_SHOW', 'No show')], db_index=True, default='SCHEDULED', max_length=20),
        ),
        migrations.AddIndex(
            model_name='medicalappointment',
            index=models.Index(fields=['company', 'practitioner_assignment', 'scheduled_start'], name='med_appt_assign_start'),
        ),
        migrations.AddIndex(
            model_name='medicalappointment',
            index=models.Index(fields=['company', 'practitioner_service_assignment', 'scheduled_start'], name='med_appt_service_start'),
        ),
    ]
