# Generated by Django 6.0.6 on 2026-07-30 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documenttemplate',
            name='document_type',
            field=models.CharField(choices=[('SALES_INVOICE', 'Sales invoice'), ('PURCHASE_BILL', 'Purchase bill'), ('CUSTOMER_RECEIPT', 'Customer receipt'), ('SUPPLIER_PAYMENT', 'Supplier payment'), ('JOURNAL_ENTRY', 'Journal entry')], db_index=True, max_length=40, verbose_name='Document type'),
        ),
    ]
