# Generated by Django 6.0.6 on 2026-07-30 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0009_normalize_medical_activity_profile'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='companysettings',
            name='companies_c_enable__4a1274_idx',
        ),
        migrations.AlterField(
            model_name='branch',
            name='branch_type',
            field=models.CharField(choices=[('HEAD_OFFICE', 'Head office'), ('BRANCH', 'Branch'), ('WAREHOUSE', 'Warehouse'), ('SERVICE_CENTER', 'Service center')], db_index=True, default='BRANCH', max_length=40, verbose_name='Branch type'),
        ),
        migrations.RemoveField(
            model_name='companysettings',
            name='enable_pos',
        ),
    ]
