# Generated by Django 6.0.6 on 2026-08-15 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TikTokConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=255)),
                ('avatar_url', models.URLField(blank=True, max_length=1000)),
                ('scopes', models.JSONField(blank=True, default=list)),
                ('access_token', models.TextField(blank=True, editable=False)),
                ('refresh_token', models.TextField(blank=True, editable=False)),
                ('access_token_expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('refresh_token_expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('last_synced_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'TikTok connection',
                'verbose_name_plural': 'TikTok connections',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='TikTokVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiktok_video_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('cover_image_url', models.URLField(blank=True, max_length=2000)),
                ('share_url', models.URLField(blank=True, max_length=2000)),
                ('embed_link', models.URLField(blank=True, max_length=2000)),
                ('duration', models.PositiveIntegerField(default=0)),
                ('width', models.PositiveIntegerField(default=0)),
                ('height', models.PositiveIntegerField(default=0)),
                ('like_count', models.PositiveBigIntegerField(default=0)),
                ('comment_count', models.PositiveBigIntegerField(default=0)),
                ('share_count', models.PositiveBigIntegerField(default=0)),
                ('view_count', models.PositiveBigIntegerField(default=0)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_visible', models.BooleanField(db_index=True, default=True)),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='integrations.tiktokconnection')),
            ],
            options={
                'verbose_name': 'TikTok video',
                'verbose_name_plural': 'TikTok videos',
                'ordering': ['-published_at', '-id'],
                'indexes': [models.Index(fields=['is_visible', 'published_at'], name='integration_is_visi_60fa58_idx'), models.Index(fields=['connection', 'published_at'], name='integration_connect_dc5fdc_idx')],
            },
        ),
    ]
