# Generated by Django 6.0.6 on 2026-07-30 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_companysubscription_action_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='max_pos',
        ),
    ]
