# Generated by Django 6.0.6 on 2026-07-30 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0003_whatsappcontact_whatsappconversation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappmessagelog',
            name='source_type',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('SALES_INVOICE', 'Sales Invoice'), ('PURCHASE_BILL', 'Purchase Bill'), ('CUSTOMER_PAYMENT', 'Customer Payment'), ('SUPPLIER_PAYMENT', 'Supplier Payment'), ('INVENTORY_MOVEMENT', 'Inventory Movement'), ('SYSTEM', 'System')], db_index=True, default='MANUAL', max_length=50, verbose_name='Source type'),
        ),
        migrations.AlterField(
            model_name='whatsapptemplate',
            name='category',
            field=models.CharField(choices=[('GENERAL', 'General'), ('SALES', 'Sales'), ('PURCHASES', 'Purchases'), ('TREASURY', 'Treasury'), ('ACCOUNTING', 'Accounting'), ('INVENTORY', 'Inventory'), ('CUSTOMER_SERVICE', 'Customer Service')], db_index=True, default='GENERAL', max_length=50, verbose_name='Category'),
        ),
    ]
