# Generated by Django 6.0.6 on 2026-07-26 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_backends', '0001_initial'),
        ('companies', '0005_seed_activity_profiles'),
        ('medical', '0005_migrate_legacy_patients'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicappointment',
            name='medical_patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='legacy_clinic_appointments', to='medical.medicalpatient'),
        ),
        migrations.AddIndex(
            model_name='clinicappointment',
            index=models.Index(fields=['company', 'medical_patient'], name='activity_ba_company_1e3462_idx'),
        ),
    ]
