# Generated by Django 6.0.6 on 2026-07-30 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_salescreditnote_allocated_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesinvoice',
            name='source',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('SALES_ORDER', 'Sales order'), ('ONLINE', 'Online'), ('IMPORT', 'Import'), ('API', 'API')], db_index=True, default='MANUAL', max_length=20, verbose_name='Source'),
        ),
    ]
